### ISSUE TITLE
PDF Report 1.4 - embedded error: Error 401 (SonarQube 4.5.4)

### ISSUE THREAD

**Issue by tzieleniewski** [SonarCommunity/sonar-pdf-report#17]
Hi,

During the source code inspection invoked from Jenkins I encountered 401 authorization problem. Invocation was through sonar-maven-plugin version 2.6.
When I log to SonarQube manually and access the URL, there is no problem. It seems that plugin is not authenticating. The plugin previous version was working under SonarQube 3.7.4.

Godspeed
TKZ

<pre>
[DEBUG] [14:22:38.760] Resorting to protocol version default close connection policy
[DEBUG] [14:22:38.760] Should NOT close connection, using HTTP/1.1
[DEBUG] [14:22:38.760] Releasing connection back to connection manager.
[DEBUG] [14:22:38.760] Freeing connection, hostConfig=HostConfiguration[host=https://test.pl]
[DEBUG] [14:22:38.760] Adding connection at: 1427718158760
[DEBUG] [14:22:38.761] Notifying no-one, there are no waiting threads
[DEBUG] [14:22:38.768] Accessing Sonar: getting violated resurces by one given rule (squid:CycleBetweenPackages)
[DEBUG] [14:22:38.914] Release semaphore on project : org.sonar.api.resources.Project@20de83dc[id=9282,key=test,qualifier=TRK], with key batch-test
[ERROR] Error 401 on https://tmpltest.sce.t-mobile.pl/sonarqube/api/issues/search?pageSize=20&componentRoots=pl.infovide:vpabx-conf&rules=squid:CycleBetweenPackages
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Can not execute Sonar
Embedded error: Error 401 on https://test.pl/sonarqube/api/issues/search?pageSize=20&componentRoots=test&rules=squid:CycleBetweenPackages
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Can not execute Sonar
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:284)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Can not execute Sonar
at org.codehaus.mojo.sonar.Bootstraper.executeMojo(Bootstraper.java:103)
at org.codehaus.mojo.sonar.Bootstraper.start(Bootstraper.java:79)
at org.codehaus.mojo.sonar.SonarMojo.execute(SonarMojo.java:88)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: org.apache.maven.plugin.MojoExecutionException: Error 401 on https://tmpltest.sce.t-mobile.pl/sonarqube/api/issues/search?pageSize=20&componentRoots=test&rules=squid:CycleBetweenPackages
at org.sonar.maven.ExceptionHandling.handle(ExceptionHandling.java:37)
at org.sonar.maven.SonarMojo.execute(SonarMojo.java:175)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.codehaus.mojo.sonar.Bootstraper.executeMojo(Bootstraper.java:98)
... 21 more
Caused by: org.sonar.wsclient.base.HttpException: Error 401 on https://tmpltest.sce.t-mobile.pl/sonarqube/api/issues/search?pageSize=20&componentRoots=test&rules=squid:CycleBetweenPackages
at org.sonar.wsclient.internal.HttpRequestFactory.execute(HttpRequestFactory.java:153)
at org.sonar.wsclient.internal.HttpRequestFactory.get(HttpRequestFactory.java:129)
at org.sonar.wsclient.issue.internal.DefaultIssueClient.find(DefaultIssueClient.java:49)
at org.sonar.report.pdf.builder.RuleBuilder.loadViolatedResources(RuleBuilder.java:105)
at org.sonar.report.pdf.builder.ProjectBuilder.initMostViolatedRulesFromNode(ProjectBuilder.java:248)
at org.sonar.report.pdf.builder.ProjectBuilder.initMostViolatedRules(ProjectBuilder.java:175)
at org.sonar.report.pdf.builder.ProjectBuilder.initializeProject(ProjectBuilder.java:98)
at org.sonar.report.pdf.PDFReporter.getProject(PDFReporter.java:132)
at org.sonar.report.pdf.PDFReporter.getReport(PDFReporter.java:82)
at org.sonar.report.pdf.batch.PDFGenerator.execute(PDFGenerator.java:109)
at org.sonar.report.pdf.batch.PDFPostJob.executeOn(PDFPostJob.java:70)
at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:72)
at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:61)
at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:132)
at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:194)
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:233)
at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228)
at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:221)
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64)
at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51)
at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125)
at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173)
at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:606)
at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
at java.security.AccessController.doPrivileged(Native Method)
at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
at org.sonar.runner.api.Runner.execute(Runner.java:100)
at org.sonar.maven.SonarMojo.execute(SonarMojo.java:173)
... 23 more
</pre>

**Comment by jdcoffre** [comment]
Note that this problem makes SonarQube analysis fails as soon as you force SonarQube authentication (sonar.forceAuthentication=true) whatever the provided user/pwd.

**Comment by dixitmehuls** [comment]
Any plan to fix this ? Do we have any timeline for the same... This makes the system unusable

**Comment by mounirfrs** [comment]
Hi I've got the same error, when activating PDF report the job fails cause of 401 error that have the same traces as mentionned in the first comment.
Making some reseach and investigating the issue on source code i've found that in the class
RuleBuilder function loadViolatedResources we have this code:
```  
    SonarClient client = SonarClient.create(this.credentials.getUrl());
    IssueClient issueClient = client.issueClient();

    IssueQuery issueQuery = IssueQuery.create();
    issueQuery.componentRoots(new String[] { projectKey });

    issueQuery.rules(new String[] { ruleKey });

    Issues issues = issueClient.find(issueQuery);
```
Must provide username and password to the client so the code will be as following:
```
     SonarClient client = SonarClient.builder()
      .url(this.credentials.getUrl())
      .login(this.credentials.getUsername())
      .password(this.credentials.getPassword())
      .build();
    
    IssueClient issueClient = client.issueClient();

    IssueQuery issueQuery = IssueQuery.create();
    issueQuery.componentRoots(new String[] { projectKey });

    issueQuery.rules(new String[] { ruleKey });

    Issues issues = issueClient.find(issueQuery);
```
